# Generated by Django 6.0.6 on 2026-07-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
